const itemData = [
    {
      id: "one",
      image: "images/1.png",
      name: "Iphone 14",
      description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
      price: 400,
    },
    {
      id: "two",
      image: "images/2.png",
      name: "Macbook air",
      description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
      price: 900,
    },
    {
      id: "three",
      image: "images/3.png",
      name: "canon m2",
      description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
      price: 499,
    },
    {
      id: "four",
      image: "images/4.png",
      name: "Armani",
      description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
      price: 500,
    },
    {
      id: "five",
      image: "images/5.png",
      name: "LED",
      description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
      price: 405,
    },
    {
      id: "six",
      image: "images/6.webp",
      name: "Nike",
      description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
      price: 389,
    },
    {
      id: "seven",
      image: "images/7.webp",
      name: "Gulf",
      description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
      price: 456,
    },
    {
      id: "eigth",
      image: "images/8.webp",
      name: "Cap",
      description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
      price: 879,
    },
  ];